import type { NextPage } from 'next';
import Head from 'next/head';
import NavBar from '../components/NavBar';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <div className="container mx-auto prose">
        <h1> Time off tracker </h1>
      </div>
    </div>
  );
};

export default Home;
